const app=document.getElementById('app');
let page='dashboard';
let status={processed:0,total:1000000,percent:0,matched:0,ambiguous:0,unmatched:0,phase:'Not started',rows_per_second:0,elapsed_seconds:0,eta_seconds:0,threads:0,batch_size:50000,cpu:0,ram:0,gpu:'Auto'};
const cols=['uuid','person_id','first_name','middle_name','middle_initial','last_name','birthdate','region_code','province_code','city_code','barangay_code','poverty_status','pcn','sex'];
const fmt=n=>Number(n||0).toLocaleString();
function login(){app.innerHTML=`<section class="login"><div class="hero"><span class="chip blue">Enterprise v12 Alpha</span><h1>DMS Name Matching Enterprise</h1><p>Premium, auditable, high-performance name matching workflow for deduplication, exact matching, fuzzy matching, live monitoring, result writing, and reconciliation.</p><div class="grid" style="margin-top:28px"><div class="card span4 blue"><h3>Exact first</h3><p>L1-L4 run before fuzzy, with accepted records removed from weaker levels.</p></div><div class="card span4 purple"><h3>Transparent scoring</h3><p>Separate FN, MN, LN scores with match evidence and ambiguity reasons.</p></div><div class="card span4 green"><h3>Live monitor</h3><p>Progress, throughput, CPU, RAM, batch, ETA and running matched results.</p></div></div></div><div class="login-card"><h2>Sign in</h2><p>Local alpha session. Full user database and roles will connect to MySQL admin schema.</p><div class="field"><label>User</label><input class="input" id="user" value="admin"></div><div class="field"><label>Password</label><input class="input" id="pass" type="password" value="admin"></div><button class="btn" onclick="signin()" style="width:100%">Sign in</button></div></section>`}
async function signin(){await fetch('/api/login',{method:'POST'});render('dashboard')}
function shell(content,title='Dashboard'){app.innerHTML=`<section class="shell"><aside class="side"><div class="brand"><div class="logo"></div><div><strong>DMS Name Matching</strong><span>Enterprise v12 Alpha</span></div></div><nav class="nav">${['dashboard','new job','live monitor','results','history','help'].map(x=>`<button class="${page===x?'active':''}" onclick="render('${x}')">${x.replace(/\b\w/g,m=>m.toUpperCase())}</button>`).join('')}</nav></aside><main class="main"><div class="top"><div><h2>${title}</h2><p style="color:#64748b;margin:6px 0 0">Professional matching workspace with guided terminology and process explanations.</p></div><button class="btn secondary" onclick="startJob()">Run Demo Job</button></div>${content}</main></section>`}
function card(label,value,cls=''){return `<div class="card span3 ${cls}"><p>${label}</p><div class="metric">${value}</div></div>`}
function dashboard(){shell(`<div class="grid">${card('Processed',fmt(status.processed),'blue')}${card('Matched',fmt(status.matched),'green')}${card('Ambiguous',fmt(status.ambiguous),'amber')}${card('Rows/sec',fmt(status.rows_per_second),'purple')}<div class="card span8"><h3>Overall Progress</h3><p>${status.phase}</p><div class="progress"><div class="bar" style="width:${status.percent}%"></div></div><p><b>${status.percent.toFixed(2)}%</b> · ${fmt(status.processed)} of ${fmt(status.total)} rows · ETA ${fmt(status.eta_seconds)} sec</p></div><div class="card span4"><h3>Specs Used</h3><p>Threads: <b>${status.threads}</b><br>Batch size: <b>${fmt(status.batch_size)}</b><br>CPU: <b>${status.cpu}%</b><br>RAM: <b>${status.ram}%</b><br>GPU: <b>${status.gpu}</b></p></div><div class="card span12"><h3>Current Matching Design</h3><p>Pipeline: Validate → Normalize → Blocking → Dedup → Exact L1-L4 → Remove accepted → Fuzzy L5-L7 → Bulk write → Reconcile → Report.</p></div></div>`,'Dashboard')}
function newJob(){shell(`<div class="wizard"><div class="steps">${['1 Login context','2 MySQL connection','3 Data sources','4 Field mapping','5 Extra fields JSON','6 Destination table','7 Matching levels','8 Review and run'].map((s,i)=>`<div class="step ${i<4?'on':''}">${s}</div>`).join('')}</div><div class="card"><h3>New Matching Job</h3><div class="help"><b>How to use:</b> connect using only user/password, choose database and table from dropdown, map required fields dynamically, define extra fields, then create or validate destination table.</div><div class="form-grid" style="margin-top:18px"><div class="field"><label>MySQL User</label><input class="input" value="root"></div><div class="field"><label>Password</label><input class="input" type="password"></div><div class="field"><label>Database</label><select>${['Bucket2_List','name_matching','cbms_2024','uplift'].map(x=>`<option>${x}</option>`)}</select></div><div class="field"><label>Table</label><select>${['tbl_person','cbms_person_processed','tbl_person_paid','4ps_active_roster'].map(x=>`<option>${x}</option>`)}</select></div>${['Unique ID','First Name','Middle Name','Last Name','Birthdate','Middle Initial'].map((x,i)=>`<div class="field"><label>${x}</label><select>${cols.map(c=>`<option ${i===0&&c==='person_id'?'selected':''}>${c}</option>`)}</select></div>`).join('')}<div class="field" style="grid-column:1/-1"><label>Extra Fields JSON</label><textarea rows="5">{\n  "source_fields": {"uuid":"source_uuid", "region_code":"source_region_code"},\n  "base_fields": {"pcn":"matched_pcn", "poverty_status":"matched_poverty_status"}\n}</textarea></div><div class="field"><label>Destination Database</label><select><option>name_matching</option></select></div><div class="field"><label>Create Result Table</label><input class="input" value="matched_results_20260922"></div></div><button class="btn" onclick="startJob()">Start Matching</button></div></div>`,'New Job')}
function monitor(){shell(`<div class="grid"><div class="card span12"><h3>Live Processing</h3><p>${status.phase}</p><div class="progress"><div class="bar" style="width:${status.percent}%"></div></div></div>${card('Processed',fmt(status.processed),'blue')}${card('Matched',fmt(status.matched),'green')}${card('Ambiguous',fmt(status.ambiguous),'amber')}${card('Unmatched',fmt(status.unmatched),'rose')}<div class="card span12"><h3>Running Matched Results</h3><table class="table"><thead><tr><th>Level</th><th>Type</th><th>Source Name</th><th>Matched Name</th><th>Score</th><th>Evidence</th></tr></thead><tbody>${sampleRows()}</tbody></table></div></div>`,'Live Monitor')}
function sampleRows(){return [['L1','Exact','JUAN DELA CRUZ','JUAN DELA CRUZ','100.00','FN+MN+LN+DOB exact'],['L5','Fuzzy','MERCIDITA PENALOSA ALAGON','MERCEDITA PENALOSA ALAGON','97.80','Fuzzy FN, exact MN/LN/DOB'],['L7','Fuzzy Near DOB','MARIA SANTOS REYES','MARIE SANTOS REYES','95.40','Name fuzzy + DOB within window']].map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}
function results(){shell(`<div class="grid"><div class="card span12"><h3>Result Table Design</h3><p>Output columns include source values, matched/base values, level, exact/fuzzy type, FN/MN/LN scores, final percentage, DOB difference, candidate count, ambiguity reason, JSON extra fields, processed_by and processed_at.</p></div></div>`,'Results')}
function history(){shell(`<div class="card"><h3>Job History</h3><p>History will consolidate every run by operator, configuration fingerprint, source table, destination table, elapsed time, rows/sec, status and report links.</p></div>`,'History')}
function help(){shell(`<div class="grid"><div class="card span6"><h3>Terminology</h3><p><b>Blocking</b> reduces candidate comparisons using DOB, name prefix, phonetic keys or geo keys.<br><b>Candidate cap</b> prevents huge fuzzy pools from auto-accepting.<br><b>Score margin</b> checks whether best match is clearly better than second best.</p></div><div class="card span6"><h3>Algorithms</h3><p><b>Exact</b> compares normalized fields directly.<br><b>Fuzzy</b> scores first, middle and last names separately.<br><b>Near DOB</b> uses year ±5, month ±3, day ±3.</p></div></div>`,'Help Center')}
async function startJob(){await fetch('/api/job/start',{method:'POST'});render('live monitor');poll()}
async function poll(){try{status=await (await fetch('/api/job/status')).json();if(page==='dashboard')dashboard();if(page==='live monitor')monitor();}catch(e){}setTimeout(poll,1200)}
function render(p){page=p;if(p==='dashboard')dashboard();else if(p==='new job')newJob();else if(p==='live monitor')monitor();else if(p==='results')results();else if(p==='history')history();else help()}
login();poll();
