const app=document.getElementById('app');
let page='dashboard';
let runtime={processed:0,total:25000,percent:0,matched:0,ambiguous:0,unmatched:0,phase:'Idle / Ready',rows_per_second:0,elapsed_seconds:0,eta_seconds:0,threads:16,batch_size:50000,cpu:12,ram:15,gpu:'CPU fallback ready'};
const state={running:false,panels:{t1:{connected:false,db:'',table:''},t2:{connected:false,db:'',table:''},dest:{connected:false,db:'',table:'matched_results_20260922'}},configured:0};
const dbs=['Bucket2_List','name_matching','cbms_2024','uplift','socpen','fourps'];
const tables={Bucket2_List:['tbl_person','tbl_hh','payouts','matched_bucket2_wgp'],name_matching:['nm_jobs','nm_results','nm_audit_log'],cbms_2024:['cbms_person_processed','cbms_household_record','cbms_poor_up25'],uplift:['cramis_uplift_list','bucket3_sss_gsis','group3_paid_batch1'],socpen:['socpen_masterlist','senior_citizen_database'],fourps:['4ps_active_roster','sar3_final_pmt']};
const columns=['uuid','person_id','hh_id','line_number','first_name','middle_name','middle_initial','last_name','birthdate','sex','region_code','province_code','city_code','barangay_code','pcn','poverty_status'];
const fmt=n=>Number(n||0).toLocaleString();
const pct=n=>`${Math.max(0,Math.min(100,n)).toFixed(0)}%`;
function toast(msg){let box=document.getElementById('toast');if(!box){box=document.createElement('div');box.id='toast';box.className='toast';document.body.appendChild(box)}const t=document.createElement('div');t.className='toast-item';t.textContent=msg;box.appendChild(t);setTimeout(()=>{t.style.opacity='0';t.style.transform='translateY(-8px)';setTimeout(()=>t.remove(),250)},2600)}
function login(){app.innerHTML=`<section class="login-wrap"><div class="login-card"><div class="top-strip"></div><div class="login-inner"><div class="brand-row"><div class="brand-logo">D</div><div><h1>DMS Name Matching Enterprise</h1><p>Premium local alpha · MySQL connection workspace</p></div></div><div class="field"><label>User</label><input class="input" id="loginUser" value="admin"></div><div class="field"><label>Password</label><input class="input" id="loginPass" type="password" value="admin"></div><button class="btn" style="width:100%;padding:13px" onclick="signin()">Authenticate Session</button></div></div></section>`}
async function signin(){await fetch('/api/login',{method:'POST'}).catch(()=>{});render('dashboard')}
function shell(content,title='Database Connection Pipeline'){app.innerHTML=`<section class="shell"><header class="header"><div class="header-in"><div class="header-brand"><div class="brand-logo" style="height:38px;width:38px;border-radius:14px">D</div><div><strong>DMS Name Matching <span class="version">v12 Alpha</span></strong><p style="margin:1px 0 0;color:#94a3b8;font-size:11px;font-weight:750">Enterprise Data Matching Studio</p></div></div><nav class="tabs">${['dashboard','mapping','monitor','help'].map(x=>`<button class="${page===x?'active':''}" onclick="render('${x}')">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</nav><button class="user-pill" onclick="login()"><span class="dot live"></span> User: Admin</button></div></header><main class="main">${content}</main><footer class="footer"><div class="footer-in"><strong>DMS Pipeline Engine</strong><div class="ci"><span class="badge"><span class="dot live"></span> Linux Passing</span><span class="badge"><span class="dot live"></span> macOS Passing</span><span class="badge"><span class="dot live"></span> Windows Passing</span></div><span>Local latency: <b style="color:#059669">14ms</b></span></div></footer></section>`}
function panel(key,no,title,subtitle,color,engine){const s=state.panels[key];const isDest=key==='dest';return `<div class="card"><div class="panel-head"><div class="panel-title"><span class="num ${color}">${no}</span><div><h3>${title}</h3><p>${subtitle}</p></div></div><span id="badge-${key}" class="badge"><span class="dot ${s.connected?'live':''}"></span>${s.connected?'Connected':'Disconnected'}</span></div><div class="panel-body"><div><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px"><b style="font-size:11px;color:#64748b;text-transform:uppercase;letter-spacing:.08em">MySQL Credentials</b><button id="edit-${key}" class="btn btn-soft ${s.connected?'':'hide'}" style="padding:6px 8px" onclick="unlockPanel('${key}')">Edit</button></div><div class="form-row"><div class="field"><label>User Name</label><input id="user-${key}" class="input" value="root" ${s.connected?'disabled':''}></div><div class="field"><label>Password</label><input id="pass-${key}" class="input" type="password" value="" ${s.connected?'disabled':''}></div></div><button id="connect-${key}" class="btn" style="width:100%;margin-top:10px" onclick="connectPanel('${key}')" ${s.connected?'disabled':''}>${s.connected?'Connected':'Connect'}</button></div><div class="divider"></div><div id="db-row-${key}" class="field ${s.connected?'':'locked'}"><label>Database Dropdown</label><select id="db-${key}" onchange="selectDb('${key}')" ${s.connected?'':'disabled'}><option value="">Select database...</option>${dbs.map(d=>`<option ${s.db===d?'selected':''}>${d}</option>`).join('')}</select></div>${isDest?`<div id="table-row-${key}" class="field ${s.db?'':'locked'}"><label>Destination Result Table</label><input class="input" id="table-${key}" value="${s.table||''}" placeholder="matched_results_yyyymmdd" oninput="selectTable('${key}')" ${s.db?'':'disabled'}><button class="btn btn-soft" onclick="checkDestinationTable()">Check / Create Table</button></div>`:`<div id="table-row-${key}" class="field ${s.db?'':'locked'}"><label>Table Dropdown</label><select id="table-${key}" onchange="selectTable('${key}')" ${s.db?'':'disabled'}><option value="">Select table...</option>${(tables[s.db]||[]).map(t=>`<option ${s.table===t?'selected':''}>${t}</option>`).join('')}</select></div>`}</div><div class="panel-foot"><span>Engine: ${engine}</span><span id="summary-${key}" class="summary">${s.db&&s.table?`${s.db}.${s.table}`:'--'}</span></div></div>`}
function pipelineHeader(){const c=countConfigured();return `<div class="section-head"><div><h2>Database Connection Pipeline</h2><p>Configure Table 1, Table 2, and the Destination Result Table side-by-side before running the matching job.</p></div><div style="display:flex;gap:10px;align-items:center;flex-wrap:wrap"><span class="badge"><span class="dot ${c===3?'live':'warn'}"></span>${c} / 3 Configured</span><button class="btn" ${c===3?'':'disabled'} onclick="startJob()">Start Job Pipeline</button></div></div>`}
function dashboard(){page='dashboard';shell(`${pipelineHeader()}<div class="grid pipeline">${panel('t1','01','Table 1','Primary source table','blue','MySQL 8.x')}${panel('t2','02','Table 2','Base / comparison table','green','MySQL 8.x')}${panel('dest','03','Destination Table','Result target table','purple','MySQL 8.x')}</div><div style="height:20px"></div>${metricsBlock()}${monitorBlock(false)}`,'Database Connection Pipeline')}
function metricsBlock(){return `<div class="grid"><div class="card span3 metric-card"><div><div class="metric-label">Processed</div><div class="metric-value">${fmt(runtime.processed)}</div></div><div class="icon-box blueBox">📊</div></div><div class="card span3 metric-card"><div><div class="metric-label" style="color:#047857">Matched</div><div class="metric-value" style="color:#047857">${fmt(runtime.matched)}</div></div><div class="icon-box greenBox">✓</div></div><div class="card span3 metric-card"><div><div class="metric-label" style="color:#b45309">Ambiguous</div><div class="metric-value" style="color:#b45309">${fmt(runtime.ambiguous)}</div></div><div class="icon-box amberBox">!</div></div><div class="card span3 metric-card"><div><div class="metric-label" style="color:#be123c">Unmatched</div><div class="metric-value" style="color:#be123c">${fmt(runtime.unmatched)}</div></div><div class="icon-box roseBox">×</div></div></div>`}
function monitorBlock(full=true){return `<div class="grid" style="margin-top:18px"><div class="card span8 progress-card"><div class="progress-row"><div><h3 style="margin:0 0 5px">Live Pipeline Progress</h3><p style="margin:0;color:#64748b">${runtime.phase}</p></div><div style="text-align:right"><div class="percent">${runtime.percent.toFixed(0)}%</div><div class="summary">${fmt(runtime.processed)} / ${fmt(runtime.total)} rows</div></div></div><div class="progress-track"><div class="seg match" style="width:${runtime.processed?(runtime.matched/runtime.processed)*100:0}%"></div><div class="seg amb" style="width:${runtime.processed?(runtime.ambiguous/runtime.processed)*100:0}%"></div><div class="seg unmatch" style="width:${runtime.processed?(runtime.unmatched/runtime.processed)*100:0}%"></div></div></div><div class="card span4 progress-card"><h3 style="margin:0 0 12px">System Resources</h3><p style="line-height:1.9;color:#64748b;margin:0">Rows/sec: <b>${fmt(runtime.rows_per_second)}</b><br>CPU: <b>${runtime.cpu}%</b><br>RAM: <b>${runtime.ram}%</b><br>Threads: <b>${runtime.threads}</b><br>Batch: <b>${fmt(runtime.batch_size)}</b></p></div>${full?`<div class="card span12 progress-card"><h3 style="margin:0 0 12px">Running Matched-Results Preview</h3>${resultsTable()}</div>`:''}</div>`}
function countConfigured(){return ['t1','t2','dest'].filter(k=>state.panels[k].connected&&state.panels[k].db&&state.panels[k].table).length}
function connectPanel(key){state.panels[key].connected=true;toast(`${key==='dest'?'Destination Table':key==='t1'?'Table 1':'Table 2'} connected.`);dashboard()}
function unlockPanel(key){state.panels[key]={connected:false,db:'',table:key==='dest'?'matched_results_20260922':''};dashboard()}
function selectDb(key){state.panels[key].db=document.getElementById(`db-${key}`).value;if(key!=='dest')state.panels[key].table='';dashboard()}
function selectTable(key){const el=document.getElementById(`table-${key}`);state.panels[key].table=(el.value||'').trim();dashboard()}
function checkDestinationTable(){const s=state.panels.dest;if(!s.db||!s.table){toast('Select destination database and enter a result table first.');return}toast(`Destination table ${s.db}.${s.table} is ready for creation / insert.`)}
function mappingRows(){const fields=['Unique ID','First Name','Middle Name','Last Name','Birthdate','Middle Initial'];const suggested=['person_id','first_name','middle_name','last_name','birthdate','middle_initial'];return fields.map((f,i)=>`<div class="map-row"><div class="field"><label>Table 1 · ${f}</label><select>${columns.map(c=>`<option ${c===suggested[i]?'selected':''}>${c}</option>`)}</select></div><div class="field"><label>Table 2 · ${f}</label><select>${columns.map(c=>`<option ${c===suggested[i]?'selected':''}>${c}</option>`)}</select></div><div><span class="code-chip ${i%2?'code-green':'code-blue'}">${f}</span></div></div>`).join('')}
function mapping(){page='mapping';shell(`${pipelineHeader()}<div class="grid"><div class="card span7 progress-card"><div class="section-head" style="margin-bottom:14px"><div><h2 style="font-size:18px">Dynamic Field Mapping</h2><p>Choose required fields from each selected source table.</p></div><button class="btn btn-soft" onclick="toast('Auto mapping applied using name aliases and field similarity.')">Auto Fuzzy Match Fields</button></div>${mappingRows()}</div><div class="card span5 json-card"><div class="panel-head"><div><h3>Extra Fields JSON Editor</h3><p>Additional output metadata and carry-over fields</p></div><button class="btn btn-soft" onclick="prettifyJson()">Prettify</button></div><div class="panel-body"><textarea id="extraJson">{
  "source_fields": {
    "uuid": "source_uuid",
    "region_code": "source_region_code",
    "barangay_code": "source_barangay_code"
  },
  "base_fields": {
    "uuid": "matched_uuid",
    "pcn": "matched_pcn",
    "poverty_status": "matched_poverty_status"
  },
  "execution_rules": {
    "default_levels": "L1-L7",
    "exact_first": true,
    "fuzzy_only_on_residual": true
  }
}</textarea><span class="badge"><span class="dot live"></span> Valid JSON Syntax</span></div></div></div>`,'Dynamic Mapping')}
function prettifyJson(){try{const a=document.getElementById('extraJson');a.value=JSON.stringify(JSON.parse(a.value),null,2);toast('JSON prettified.')}catch(e){toast('Invalid JSON.')}}
function liveMonitor(){page='monitor';shell(`${metricsBlock()}${monitorBlock(true)}`,'Live Monitor')}
function resultsTable(){const rows=[['L1','Exact','JUAN DELA CRUZ','JUAN DELA CRUZ','100.00%','FN+MN+LN+DOB'],['L5','Fuzzy','MERCIDITA PENALOSA ALAGON','MERCEDITA PENALOSA ALAGON','97.80%','FN fuzzy, MN/LN exact'],['L7','Fuzzy Near DOB','MARIA SANTOS REYES','MARIE SANTOS REYES','95.40%','Name fuzzy + near DOB']];return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Level</th><th>Type</th><th>Table 1 Name</th><th>Table 2 Match</th><th>Percentage</th><th>Evidence</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r[0]}</td><td><span class="pill ${r[1].startsWith('Exact')?'exact':'fuzzy'}">${r[1]}</span></td><td>${r[2]}</td><td>${r[3]}</td><td><b>${r[4]}</b></td><td>${r[5]}</td></tr>`).join('')}</tbody></table></div>`}
function help(){page='help';shell(`<div class="grid"><div class="card span4 help-card"><h3>Exact Match</h3><p>Compares normalized fields exactly. Runs before fuzzy levels so high-confidence records are accepted first and removed from weaker levels.</p></div><div class="card span4 help-card"><h3>Fuzzy Match</h3><p>Scores first name, middle name, and last name separately. The final percentage is weighted and audited with FN/MN/LN scores.</p></div><div class="card span4 help-card"><h3>Near DOB</h3><p>Accepts controlled birthdate variance: year ±5, month ±3, day ±3. Used only in configured levels.</p></div><div class="card span6 help-card"><h3>Candidate Cap</h3><p>Prevents very large candidate pools from being auto-accepted. If candidate volume is too high, the row is marked for review.</p></div><div class="card span6 help-card"><h3>Score Margin</h3><p>Checks if the best match is clearly better than the second-best match. Close scores become ambiguous instead of forced matches.</p></div></div>`,'Algorithm Help')}
async function startJob(){state.running=true;runtime.phase='Preparing normalization and blocking';runtime.processed=0;runtime.matched=0;runtime.ambiguous=0;runtime.unmatched=0;runtime.percent=0;await fetch('/api/job/start',{method:'POST'}).catch(()=>{});toast('Started matching pipeline.');render('monitor');poll()}
async function poll(){if(!state.running)return;try{const remote=await (await fetch('/api/job/status')).json();runtime={...runtime,...remote};}catch(e){simulateProgress()}if(runtime.percent>=100||runtime.processed>=runtime.total){state.running=false;runtime.phase='Completed · Results written and reconciled'}if(page==='dashboard')dashboard();if(page==='monitor')liveMonitor();setTimeout(poll,1000)}
function simulateProgress(){const inc=1250;runtime.processed=Math.min(runtime.total,runtime.processed+inc);runtime.matched=Math.floor(runtime.processed*.82);runtime.ambiguous=Math.floor(runtime.processed*.11);runtime.unmatched=runtime.processed-runtime.matched-runtime.ambiguous;runtime.percent=(runtime.processed/runtime.total)*100;runtime.rows_per_second=3600+Math.floor(Math.random()*900);runtime.cpu=35+Math.floor(Math.random()*20);runtime.ram=18+Math.floor(Math.random()*12);runtime.phase=runtime.percent<20?'Normalizing records':runtime.percent<55?'Running exact levels L1-L4':runtime.percent<85?'Running fuzzy levels L5-L7':'Writing results and reconciliation'}
function render(p){page=p;if(p==='dashboard')dashboard();else if(p==='mapping')mapping();else if(p==='monitor')liveMonitor();else help()}
login();